import { GAME_CONFIG } from './constants.js';

/**
 * Provides level-specific parameters and rules.
 */
export const LevelSettings = {
  colors: {
    totalDots: GAME_CONFIG.COLORS_LEVEL_CONFIG?.TOTAL_DOTS || 85,
    targetDots: GAME_CONFIG.COLORS_LEVEL_CONFIG?.TARGET_DOTS || 17,
    distractorDots: GAME_CONFIG.COLORS_LEVEL_CONFIG?.DISTRACTOR_DOTS || 68,
    dispersionFrames: GAME_CONFIG.COLORS_LEVEL_CONFIG?.DISPERSION_FRAMES || 30,
    bounceDampening: GAME_CONFIG.COLORS_LEVEL_CONFIG?.DOT_BOUNCE_DAMPENING || 0.98,
    shimmerFreq: GAME_CONFIG.COLORS_LEVEL_CONFIG?.SHIMMER_FREQUENCY || 0.05,
    glowFreq: GAME_CONFIG.COLORS_LEVEL_CONFIG?.GLOW_FREQUENCY || 0.1,
    memoryTime: GAME_CONFIG.COLORS_LEVEL_CONFIG?.MEMORY_DISPLAY_TIME || 2000,
    collisionDelay: GAME_CONFIG.COLORS_LEVEL_CONFIG?.COLLISION_ENABLED_DELAY || 250
  },
  text: {
    centerFontSize: GAME_CONFIG.TEXT_LEVEL_CONFIG?.CENTER_FONT_SIZE || 900,
    fallingFontSize: GAME_CONFIG.TEXT_LEVEL_CONFIG?.FALLING_FONT_SIZE || 240,
    spawnEdgeBuffer: GAME_CONFIG.TEXT_LEVEL_CONFIG?.SPAWN_EDGE_BUFFER || 50,
    advanceCount: GAME_CONFIG.TEXT_LEVEL_CONFIG?.TARGET_ADVANCE_COUNT || 5,
    checkpointInterval: GAME_CONFIG.TEXT_LEVEL_CONFIG?.CHECKPOINT_INTERVAL || 5,
    abilities: GAME_CONFIG.TEXT_LEVEL_CONFIG?.ABILITIES || ['laser','aoe','charge_up'],
    aoeRadius: GAME_CONFIG.TEXT_LEVEL_CONFIG?.AOE_RADIUS || 200,
    chargeDuration: GAME_CONFIG.TEXT_LEVEL_CONFIG?.CHARGE_UP_DURATION || 60,
    laserWidth: GAME_CONFIG.TEXT_LEVEL_CONFIG?.LASER_WIDTH || [3,5],
    swirlCount: GAME_CONFIG.TEXT_LEVEL_CONFIG?.SWIRL_PARTICLE_COUNT || 30,
    orbitRadius: GAME_CONFIG.TEXT_LEVEL_CONFIG?.CENTER_PIECE_ORBIT_RADIUS || 100
  }
};
